# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "imdt-flir-boson"
BBFILE_PATTERN_imdt-flir-boson = "^${LAYERDIR}/"
BBFILE_PRIORITY_imdt-flir-boson = "10"

LAYERSERIES_COMPAT_imdt-flir-boson = "hardknott scarthgap"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_imdt-flir-boson = "1"

LAYERDEPENDS_imdt-flir-boson = "core"

REQUIRED_POKY_BBLAYERS_CONF_VERSION = "2"
